### ISSUE TITLE
Could not find the type or namespace name 'DevILSharp"?Please provide DevILSharp.dll

### ISSUE THREAD

**Issue by Robintjhb** [vrvis/aardvark.base#24]
Could not find the type or namespace name 'DevILSharp":did not provide DevILSharp.dll,
Please provide DevILSharp.dll

**Comment by haraldsteinlechner** [comment]
In the aardvark libraries we use the build system to download third party librarires such as DevILSharp (https://www.nuget.org/packages/DevILSharp/)
Just like many other modern F# (also C#) projects we use Paket (https://fsprojects.github.io/Paket/) for resolving packages during build and Fake (http://fsharp.github.io/FAKE/) for specifying build tasks. the build can be invoked by using either build.cmd (win) or build.sh (linux).

**Comment by Robintjhb** [comment]
Thanks to your help,that solve my problem, Happy New Year
